### ISSUE TITLE
last commit message button affects all loaded repositories

### ISSUE THREAD

**Issue by MFueg** [JanBN/vscode-git-last-commit-message#1]
# Versions

Extension: 1.7.0
VS Code:   1.37.1

# Description
1. I select a repository inside the git side menu
2. Then I click on the extensions' button to paste the last commit message
3. The extension overwrites all commit messages of all available repositories

The Problem is that if I for example go to a repository and begin to write a new commit message and then try to paste the last message of a different repository, my new message of the first repository will be overwritten.

It would be great, if only the current selected repository's commit message will be overwritten.

Apart from that: A helpful extension! Thanks a lot.

![git-commit-paste-bug](https://user-images.githubusercontent.com/47006140/63438445-95107680-c42c-11e9-982d-5a24906ee332.gif)

**Comment by JanBN** [comment]
Hello,

this is the maximum I can do for now. It is already published in 1.8.0 version

![image](https://user-images.githubusercontent.com/7447593/69624066-40405580-1044-11ea-98c4-ec9dc05c8395.png)
